[tool.poetry]
name = "app"
version = "0.2.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
enum34 = "==1.1.8"
stripe = "^2.55.1"
money = "^1.3.0"
iso4217 = "^1.6.20180829"
pyvat = "^1.3.15"
